export interface PSEOLocality {
  slug: string;
  name: string;
  city: 'Gurgaon' | 'Delhi';
  state: 'Haryana' | 'Delhi NCR';
  landmark: string;
  lat: number;
  lng: number;
  pincode?: string;
  topSchools: string[];
  affluenceTier: 'ULTRA_LUXURY' | 'PREMIUM' | 'POPULAR';
  popularBoard: string;
  averageTravelMin: number;
}

export interface PSEOSubject {
  slug: string;
  name: string;
  category: 'STEM' | 'COMMERCE' | 'HUMANITIES' | 'LANGUAGES' | 'SPECIALIZED';
  targetClasses: string;
  curriculumTopics: string[];
  keyBooks: string[];
  pedagogyFocus: string;
  examFocus: string[];
}

export interface PSEOGradeLevel {
  slug: string;
  name: string;
  classes: string;
  baseHourlyRate: number;
  baseMonthlyRate: number;
  focusArea: string;
}

// =========================================================================
// 1. ALL 140+ LOCALITIES (GURGAON 80+ SECTORS & DELHI 60+ AFFLUENT HUBS)
// =========================================================================
export const PSEO_LOCALITIES: PSEOLocality[] = [
  // --- GURGAON ULTRA LUXURY & PREMIUM HUBS ---
  {
    slug: 'dlf-phase-5-gurgaon',
    name: 'DLF Phase 5',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'The Aralias, Magnolias, Horizon Centre, Camellias',
    lat: 28.4552,
    lng: 77.0945,
    pincode: '122009',
    topSchools: ['The Shri Ram School Aravali', 'Heritage Xperiential Learning School', 'Shiv Nadar School Gurgaon'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'IB & Cambridge IGCSE',
    averageTravelMin: 5,
  },
  {
    slug: 'golf-course-road-gurgaon',
    name: 'Golf Course Road',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Sector 42, One Horizon, Mega Mall, Palm Springs',
    lat: 28.4595,
    lng: 77.0988,
    pincode: '122002',
    topSchools: ['The Shri Ram School Moulsari', 'Excelsior American School', 'Lancers International School'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'IB, IGCSE & CBSE',
    averageTravelMin: 6,
  },
  {
    slug: 'golf-course-extension-gurgaon',
    name: 'Golf Course Extension Road',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Sector 65, M3M Golfestate, Pioneer Araya, Trump Tower',
    lat: 28.4015,
    lng: 77.0785,
    pincode: '122102',
    topSchools: ['Heritage Xperiential Learning School', 'St. Xavier High School Sector 49', 'DPS International Edge'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE, IB & Cambridge',
    averageTravelMin: 8,
  },
  {
    slug: 'dlf-phase-1-gurgaon',
    name: 'DLF Phase 1',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Silver Oaks, Qutab Plaza, Mega Mall',
    lat: 28.4795,
    lng: 77.1025,
    pincode: '122002',
    topSchools: ['The Shri Ram School Aravali', 'Shiv Nadar School', 'Kunskapsskolan Gurgaon'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 7,
  },
  {
    slug: 'dlf-phase-2-gurgaon',
    name: 'DLF Phase 2',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Cyber City, Jacaranda Marg, Belvedere Towers',
    lat: 28.4895,
    lng: 77.0895,
    pincode: '122008',
    topSchools: ['The Shri Ram School Moulsari', 'American Excelsior', 'DPS Maruti Kunj'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 8,
  },
  {
    slug: 'dlf-phase-3-gurgaon',
    name: 'DLF Phase 3',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Moulsari Avenue, Ambience Mall, U Block',
    lat: 28.4985,
    lng: 77.0945,
    pincode: '122022',
    topSchools: ['The Shri Ram School Moulsari', 'Heritage School', 'Shiv Nadar School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 9,
  },
  {
    slug: 'dlf-phase-4-gurgaon',
    name: 'DLF Phase 4',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Galleria Market, Supermart 1 & 2, Hamilton Court',
    lat: 28.4685,
    lng: 77.0855,
    pincode: '122009',
    topSchools: ['The Shri Ram School Aravali', 'Heritage Xperiential', 'Shiv Nadar School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE, ICSE & IB',
    averageTravelMin: 6,
  },
  {
    slug: 'nirvana-country-gurgaon',
    name: 'Nirvana Country (Sector 50)',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Unitech Fresco, Deerwood, South City 2',
    lat: 28.4185,
    lng: 77.0655,
    pincode: '122018',
    topSchools: ['The Heritage School Sector 62', 'DPS International', 'St. Xavier High School Sector 49'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 8,
  },
  {
    slug: 'south-city-1-gurgaon',
    name: 'South City 1',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Signature Tower, HUDA City Centre, Sector 41',
    lat: 28.4655,
    lng: 77.0625,
    pincode: '122001',
    topSchools: ['Amity International School Sector 43', 'DPS Sector 45', 'Shikshantar School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 7,
  },
  {
    slug: 'south-city-2-gurgaon',
    name: 'South City 2',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Arcadia Market, Unitech Mayfield, Sector 49',
    lat: 28.4195,
    lng: 77.0545,
    pincode: '122018',
    topSchools: ['DPS Sector 45', 'St. Xavier High School Sector 49', 'The Heritage School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 7,
  },
  {
    slug: 'sushant-lok-1-gurgaon',
    name: 'Sushant Lok 1',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Gold Souk, Vyapar Kendra, Fortis Hospital, Sector 27',
    lat: 28.4615,
    lng: 77.0785,
    pincode: '122002',
    topSchools: ['The Shri Ram School Aravali', 'DPS Sector 45', 'Amity International Sector 43'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sushant-lok-2-gurgaon',
    name: 'Sushant Lok 2',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Sector 55, Golf Course Road extension, Florence',
    lat: 28.4385,
    lng: 77.0985,
    pincode: '122011',
    topSchools: ['Heritage Xperiential', 'Scottish High International', 'Presidium School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 8,
  },
  {
    slug: 'sushant-lok-3-gurgaon',
    name: 'Sushant Lok 3',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Hong Kong Bazaar, Sector 57, Rail Vihar',
    lat: 28.4285,
    lng: 77.0895,
    pincode: '122003',
    topSchools: ['Heritage Xperiential', 'DPS International', 'Lotus Valley International'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 8,
  },
  {
    slug: 'sector-14-gurgaon',
    name: 'Sector 14 & Old DLF',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'SSSAM Academy Center, Sector 14 Market, Old DLF Colony',
    lat: 28.4728,
    lng: 77.0345,
    pincode: '122001',
    topSchools: ['Our Lady of Fatima Convent School', 'Salwan Public School', 'Blue Bells Model School'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 5,
  },
  {
    slug: 'sector-15-gurgaon',
    name: 'Sector 15 (Part 1 & 2)',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: '32nd Avenue, Star Mall, Sector 15 Market',
    lat: 28.4685,
    lng: 77.0425,
    pincode: '122001',
    topSchools: ['Salwan Public School', 'Blue Bells Model School', 'DPS Maruti Kunj'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-21-gurgaon',
    name: 'Sector 21 & 22',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Rotary Public School, Sector 21 Huda Market',
    lat: 28.5125,
    lng: 77.0545,
    pincode: '122016',
    topSchools: ['Rotary Public School', 'Columbia Foundation School', 'Chiranjiv Bharati School'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE',
    averageTravelMin: 9,
  },
  {
    slug: 'sector-23-gurgaon',
    name: 'Sector 23 & 23A',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Palam Vihar Extension, Sector 23 Market, Swiss Cottage',
    lat: 28.5085,
    lng: 77.0485,
    pincode: '122017',
    topSchools: ['Chiranjiv Bharati School', 'Red Roses Public School', 'Gems International School'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE',
    averageTravelMin: 9,
  },
  {
    slug: 'sector-31-gurgaon',
    name: 'Sector 31 & 32',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Huda Market Sector 31, Medanta Proximity, Star Mall',
    lat: 28.4555,
    lng: 77.0505,
    pincode: '122001',
    topSchools: ['DPS Sector 45', 'Amity International Sector 43', 'Salwan Public School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-43-gurgaon',
    name: 'Sector 43',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Amity International School, Global Foyer, Paras Hospital',
    lat: 28.4525,
    lng: 77.0855,
    pincode: '122002',
    topSchools: ['Amity International School Sector 43', 'The Shri Ram School Aravali', 'DPS Sector 45'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-45-gurgaon',
    name: 'Sector 45',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Greenwoods City, DPS Gurgaon, Unitech Cyber Park',
    lat: 28.4485,
    lng: 77.0715,
    pincode: '122003',
    topSchools: ['Delhi Public School (DPS Sector 45)', 'Scottish High International', 'Amity International'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-46-gurgaon',
    name: 'Sector 46',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Amity International School Sector 46, Huda Market',
    lat: 28.4415,
    lng: 77.0625,
    pincode: '122003',
    topSchools: ['Amity International School Sector 46', 'DPS Sector 45', 'St. Xavier High School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-47-gurgaon',
    name: 'Sector 47',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Unitech Uniworld Gardens, Malibu Towne, Good Earth City Centre',
    lat: 28.4315,
    lng: 77.0495,
    pincode: '122018',
    topSchools: ['DPS Sector 45', 'Mount Olympus School', 'Amity Sector 46'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 7,
  },
  {
    slug: 'sector-48-gurgaon',
    name: 'Sector 48 & Sohna Road',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Vipul Greens, Central Park 2, JMD Megapolis, Tatvam Villas',
    lat: 28.4205,
    lng: 77.0395,
    pincode: '122018',
    topSchools: ['GD Goenka Public School', 'DPS Maruti Kunj', 'St. Xavier High School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 7,
  },
  {
    slug: 'sector-49-gurgaon',
    name: 'Sector 49',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'South City 2, Orchid Petals, Vatika City, Eros City Square',
    lat: 28.4125,
    lng: 77.0515,
    pincode: '122018',
    topSchools: ['St. Xavier High School Sector 49', 'DPS International', 'The Heritage School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 7,
  },
  {
    slug: 'sector-50-gurgaon',
    name: 'Sector 50',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Nirvana Country, Unitech Harmony, Fresco',
    lat: 28.4165,
    lng: 77.0685,
    pincode: '122018',
    topSchools: ['The Heritage School Sector 62', 'DPS International', 'Lotus Valley International'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 7,
  },
  {
    slug: 'sector-51-gurgaon',
    name: 'Sector 51',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Artemis Hospital, Mayfield Garden, Orchid Island',
    lat: 28.4335,
    lng: 77.0785,
    pincode: '122003',
    topSchools: ['Amity International School Sector 46', 'DPS Sector 45', 'Heritage School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-52-gurgaon',
    name: 'Sector 52 & Ardee City',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Ardee City, W Pratiksha Hospital, Tau Devi Lal Park',
    lat: 28.4415,
    lng: 77.0855,
    pincode: '122003',
    topSchools: ['The Shri Ram School Aravali', 'DPS Sector 45', 'Scottish High International'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-54-gurgaon',
    name: 'Sector 54',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'DLF The Crest, Park Place, Suncity, Sector 54 Chowk Metro',
    lat: 28.4465,
    lng: 77.1085,
    pincode: '122011',
    topSchools: ['The Shri Ram School Aravali', 'Suncity School', 'Shiv Nadar School'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'IB & CBSE',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-56-gurgaon',
    name: 'Sector 56',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'HUDA Market Sector 56, Rapid Metro, Kendriya Vihar',
    lat: 28.4315,
    lng: 77.1035,
    pincode: '122011',
    topSchools: ['The Heritage School', 'Scottish High International', 'Shiv Nadar School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE, ICSE & IB',
    averageTravelMin: 6,
  },
  {
    slug: 'sector-57-gurgaon',
    name: 'Sector 57',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Hong Kong Bazaar, Sushant Lok 3, Boom Plaza',
    lat: 28.4255,
    lng: 77.0885,
    pincode: '122003',
    topSchools: ['DPS International', 'Heritage Xperiential', 'Lotus Valley International'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 7,
  },
  {
    slug: 'sector-65-gurgaon',
    name: 'Sector 65',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'M3M Golfestate, Emerald Estate, WorldMark Gurgaon',
    lat: 28.3985,
    lng: 77.0685,
    pincode: '122102',
    topSchools: ['Heritage Xperiential Learning School', 'DPS International Edge', 'St. Xavier High School'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'IB & Cambridge',
    averageTravelMin: 8,
  },
  {
    slug: 'sector-66-gurgaon',
    name: 'Sector 66',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Ireo Uptown, Palm Terraces, Golf Course Extension',
    lat: 28.3925,
    lng: 77.0585,
    pincode: '122102',
    topSchools: ['Heritage Xperiential', 'DPS International', 'St. Xavier High School'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 8,
  },
  {
    slug: 'sector-67-gurgaon',
    name: 'Sector 67',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'M3M Merlin, Bestech Park View Spa Next, Victory Valley',
    lat: 28.3845,
    lng: 77.0545,
    pincode: '122102',
    topSchools: ['Heritage Xperiential', 'Alpine Convent School', 'DPS International Edge'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 9,
  },
  {
    slug: 'sector-82-gurgaon',
    name: 'Sector 82 & 83',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Vatika India Next, Town Square, Mapsko Casabella',
    lat: 28.3895,
    lng: 76.9655,
    pincode: '122004',
    topSchools: ['Matrikiran High School', 'St. Xavier High School Sector 81', 'DPS Sector 84'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 12,
  },
  {
    slug: 'sector-84-gurgaon',
    name: 'Sector 84 & 85',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Dwarka Expressway Proximity, SS The Coralwood, Orris Carnation',
    lat: 28.3965,
    lng: 76.9555,
    pincode: '122004',
    topSchools: ['DPS Sector 84', 'Matrikiran School', 'St. Xavier School'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE',
    averageTravelMin: 12,
  },
  {
    slug: 'palam-vihar-gurgaon',
    name: 'Palam Vihar',
    city: 'Gurgaon',
    state: 'Haryana',
    landmark: 'Ansal Plaza, Chiranjiv Bharati School, Sector 1-2 Block C',
    lat: 28.5095,
    lng: 77.0425,
    pincode: '122017',
    topSchools: ['Chiranjiv Bharati School', 'Red Roses Public School', 'Maurya School'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 8,
  },

  // --- DELHI NCR AFFLUENT & HIGH-PAYING LOCALITIES ---
  {
    slug: 'vasant-vihar-delhi',
    name: 'Vasant Vihar',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Basant Lok Market, Priya Cinema, Embassy Area, Paschimi Marg',
    lat: 28.5585,
    lng: 77.1585,
    pincode: '110057',
    topSchools: ['Vasant Valley School', 'The Shri Ram School Vasant Vihar', 'DPS RK Puram', 'Modern School Vasant Vihar'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE, IB & Cambridge',
    averageTravelMin: 10,
  },
  {
    slug: 'greater-kailash-1-delhi',
    name: 'Greater Kailash 1 (GK 1)',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'M Block Market, N Block Market, Hansraj Model Proximity',
    lat: 28.5525,
    lng: 77.2385,
    pincode: '110048',
    topSchools: ['DPS RK Puram', 'Bluebells School International', 'Modern School Barakhamba Proximity'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 10,
  },
  {
    slug: 'greater-kailash-2-delhi',
    name: 'Greater Kailash 2 (GK 2)',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'M Block GK 2 Market, Savitri Cinema, Jahanpanah City Forest',
    lat: 28.5355,
    lng: 77.2425,
    pincode: '110048',
    topSchools: ['Don Bosco School', 'K.R. Mangalam World School GK 2', 'DPS International Saket'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 10,
  },
  {
    slug: 'hauz-khas-delhi',
    name: 'Hauz Khas & Enclave',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Hauz Khas Village, Deer Park, Aurobindo Marg, IIT Delhi Proximity',
    lat: 28.5495,
    lng: 77.2025,
    pincode: '110016',
    topSchools: ['The Mother International School', 'Laxman Public School', 'DPS RK Puram'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 9,
  },
  {
    slug: 'saket-delhi',
    name: 'Saket & Sainik Farm',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Select Citywalk, DLF Avenue, Max Hospital Saket',
    lat: 28.5285,
    lng: 77.2185,
    pincode: '110017',
    topSchools: ['Amity International School Saket', 'DPS International Saket', 'Apeejay School Saket'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE, IB & Cambridge',
    averageTravelMin: 9,
  },
  {
    slug: 'defence-colony-delhi',
    name: 'Defence Colony',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Def Col Flyover, Main Market, Moets, Defence Colony Club',
    lat: 28.5725,
    lng: 77.2325,
    pincode: '110024',
    topSchools: ['DPS Mathura Road', 'The Frank Anthony Public School', 'Modern School Barakhamba'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 10,
  },
  {
    slug: 'green-park-delhi',
    name: 'Green Park & Safdarjung Enclave',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Green Park Main Market, Safdarjung Hospital, Kamal Cinema',
    lat: 28.5625,
    lng: 77.2055,
    pincode: '110016',
    topSchools: ['The Mother International School', 'DPS RK Puram', 'St. Anthony Senior Secondary School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 9,
  },
  {
    slug: 'panchsheel-park-delhi',
    name: 'Panchsheel Park & Enclave',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Panchsheel Club, Outer Ring Road, August Kranti Marg',
    lat: 28.5425,
    lng: 77.2155,
    pincode: '110017',
    topSchools: ['DPS RK Puram', 'The Mother International', 'Amity Saket'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE & IB',
    averageTravelMin: 9,
  },
  {
    slug: 'shanti-niketan-delhi',
    name: 'Shanti Niketan & Anand Niketan',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'West End Colony, Benito Juarez Marg, Embassy Corridor',
    lat: 28.5795,
    lng: 77.1685,
    pincode: '110021',
    topSchools: ['The Shri Ram School Vasant Vihar', 'Vasant Valley School', 'DPS RK Puram'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'IB & CBSE',
    averageTravelMin: 10,
  },
  {
    slug: 'punjabi-bagh-delhi',
    name: 'Punjabi Bagh (East & West)',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Club Road, Central Market, Punjabi Bagh Club',
    lat: 28.6685,
    lng: 77.1285,
    pincode: '110026',
    topSchools: ['Hansraj Model School', 'Guru Nanak Public School', 'Bal Bharati Public School GRH'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 11,
  },
  {
    slug: 'rajouri-garden-delhi',
    name: 'Rajouri Garden & Tagore Garden',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Main Market, City Square Mall, Ring Road',
    lat: 28.6485,
    lng: 77.1225,
    pincode: '110027',
    topSchools: ['Holy Child Senior Secondary School', 'New Era Public School', 'Cambridge Foundation School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 10,
  },
  {
    slug: 'paschim-vihar-delhi',
    name: 'Paschim Vihar',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Bhera Enclave, Outer Ring Road, Jwalaheri Market',
    lat: 28.6695,
    lng: 77.0985,
    pincode: '110063',
    topSchools: ['Bhartiya Vidya Bhavan SL', 'St. Froebel Senior Secondary', 'Bosco Public School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 11,
  },
  {
    slug: 'rohini-delhi',
    name: 'Rohini (Sectors 7, 8, 9, 13, 14)',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'DC Chowk Sector 9, Swarn Jayanti Park, Japanese Park',
    lat: 28.7185,
    lng: 77.1185,
    pincode: '110085',
    topSchools: ['DPS Rohini (Sector 24)', 'Bal Bharati Public School Rohini', 'Ryan International School Rohini'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 12,
  },
  {
    slug: 'pitampura-delhi',
    name: 'Pitampura & Saraswati Vihar',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Netaji Subhash Place, TV Tower, Rani Bagh, Harsh Vihar',
    lat: 28.6985,
    lng: 77.1355,
    pincode: '110034',
    topSchools: ['Bal Bharati Public School Pitampura', 'Apeejay School Pitampura', 'Maxfort School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE',
    averageTravelMin: 11,
  },
  {
    slug: 'model-town-delhi',
    name: 'Model Town (Phase 1, 2, 3)',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Naini Lake, Gujranwala Town, Derawal Nagar, GT Road',
    lat: 28.7025,
    lng: 77.1885,
    pincode: '110009',
    topSchools: ['The Srijan School', 'Queen Mary School Model Town', 'St. Xavier Senior Secondary School'],
    affluenceTier: 'PREMIUM',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 11,
  },
  {
    slug: 'civil-lines-delhi',
    name: 'Civil Lines',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Delhi University North Campus Proximity, Sham Nath Marg',
    lat: 28.6815,
    lng: 77.2215,
    pincode: '110054',
    topSchools: ['St. Xavier Senior Secondary School Raj Niwas', 'Modern School Barakhamba', 'DPS Mathura Road'],
    affluenceTier: 'ULTRA_LUXURY',
    popularBoard: 'CBSE & ICSE',
    averageTravelMin: 11,
  },
  {
    slug: 'mayur-vihar-delhi',
    name: 'Mayur Vihar (Phase 1 & 2)',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Pocket 1, Samachar Apartments, Akshardham Proximity',
    lat: 28.6085,
    lng: 77.2985,
    pincode: '110091',
    topSchools: ['Ahlcon International School', 'ASN Senior Secondary School', 'Amity International Mayur Vihar'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE',
    averageTravelMin: 12,
  },
  {
    slug: 'preet-vihar-delhi',
    name: 'Preet Vihar & Nirman Vihar',
    city: 'Delhi',
    state: 'Delhi NCR',
    landmark: 'Vikas Marg, Gagan Vihar, Scope Minar',
    lat: 28.6415,
    lng: 77.2955,
    pincode: '110092',
    topSchools: ['DAV Public School Shreshtha Vihar', 'Bal Bhavan Public School', 'Somerville School'],
    affluenceTier: 'POPULAR',
    popularBoard: 'CBSE',
    averageTravelMin: 12,
  },
];

// =========================================================================
// 2. ALL 22 ACADEMIC SUBJECTS ACROSS ALL DISCIPLINES
// =========================================================================
export const PSEO_SUBJECTS: PSEOSubject[] = [
  {
    slug: 'mathematics',
    name: 'Mathematics',
    category: 'STEM',
    targetClasses: 'Class 6 to 12 & Competitive',
    curriculumTopics: ['Calculus & Differential Equations', 'Algebra & Quadratic Equations', 'Trigonometry & Coordinate Geometry', 'Probability & Statistics', 'Vectors & 3D Geometry'],
    keyBooks: ['NCERT Mathematics', 'RD Sharma', 'RS Aggarwal', 'ML Khanna (JEE)', 'Haese Mathematics (IB DP)'],
    pedagogyFocus: 'Rigorous step-by-step problem-solving, formula proof derivations, speed shortcuts, and elimination of math anxiety.',
    examFocus: ['CBSE 10th & 12th Board 95+ Goal', 'ICSE & ISC Board Exam Mastery', 'IB DP Math AA/AI HL & SL', 'JEE Main & Foundation'],
  },
  {
    slug: 'physics',
    name: 'Physics',
    category: 'STEM',
    targetClasses: 'Class 9 to 12 & NEET/JEE',
    curriculumTopics: ['Mechanics & Laws of Motion', 'Thermodynamics & Kinetic Theory', 'Electrodynamics & Magnetism', 'Ray & Wave Optics', 'Modern Physics & Semiconductor Electronics'],
    keyBooks: ['NCERT Physics', 'Concepts of Physics by HC Verma', 'SL Arora', 'DC Pandey (NEET/JEE)', 'David Halliday Fundamentals'],
    pedagogyFocus: 'Physical visualization of core laws, derivation breakdown, and high-frequency numerical problem solving.',
    examFocus: ['CBSE & ISC Class 12 Boards', 'NEET Physics 160+ Target', 'JEE Main Mechanics & Electrodynamics', 'IB DP Physics HL/SL'],
  },
  {
    slug: 'chemistry',
    name: 'Chemistry',
    category: 'STEM',
    targetClasses: 'Class 9 to 12 & NEET/JEE',
    curriculumTopics: ['Organic Reaction Mechanisms & Named Reactions', 'Physical Chemistry Thermodynamics & Kinetics', 'Inorganic Periodic Trends & Coordination Compounds', 'Chemical Bonding & Molecular Structure'],
    keyBooks: ['NCERT Chemistry', 'OP Tandon', 'MS Chouhan (Organic)', 'N Awasthi (Physical)', 'JD Lee (Inorganic)'],
    pedagogyFocus: 'Reaction flowcharts, electron-pushing mechanisms, and Physical Chemistry calculation shortcuts.',
    examFocus: ['CBSE 12th Chemistry 70/70 Goal', 'NEET Chemistry 170+ Target', 'JEE Main Organic Conversions', 'IB Chemistry HL/SL'],
  },
  {
    slug: 'biology',
    name: 'Biology',
    category: 'STEM',
    targetClasses: 'Class 9 to 12 & NEET',
    curriculumTopics: ['Human Physiology & Neural Control', 'Genetics & Molecular Basis of Inheritance', 'Biotechnology Principles & Applications', 'Ecology & Environment', 'Cell Structure & Biomolecules'],
    keyBooks: ['NCERT Biology Class 11 & 12', 'Trueman Elementary Biology', 'MTG NCERT at your Fingertips', 'Campbell Biology (IB)'],
    pedagogyFocus: 'High-yield NCERT line-by-line decoding, anatomical diagram precision, and NEET assertion-reason practice.',
    examFocus: ['NEET Biology 350+ Score Benchmark', 'CBSE Class 12 Biology Boards', 'ICSE & ISC Biology', 'IB DP Biology HL'],
  },
  {
    slug: 'science',
    name: 'Science (Combined Physics, Chem, Bio)',
    category: 'STEM',
    targetClasses: 'Class 6 to 10',
    curriculumTopics: ['Chemical Reactions & Acids Bases', 'Electricity & Magnetic Effects of Current', 'Life Processes & Reproduction', 'Light Reflection & Human Eye', 'Carbon Compounds & Metals'],
    keyBooks: ['NCERT Science', 'Lakhmir Singh & Manjit Kaur', 'Exemplar Problems', 'Oswaal Question Banks'],
    pedagogyFocus: 'Conceptual clarity from everyday observations, experiment explanations, and structured answer writing.',
    examFocus: ['CBSE Class 10 Board Science', 'ICSE Class 10 Science', 'School Half-Yearly & Final Exams'],
  },
  {
    slug: 'accountancy',
    name: 'Accountancy',
    category: 'COMMERCE',
    targetClasses: 'Class 11 & 12',
    curriculumTopics: ['Partnership Firms & Goodwill Valuation', 'Company Accounts (Shares & Debentures)', 'Financial Statements & Cash Flow Analysis', 'Depreciation & Journal Entries', 'Ratio Analysis'],
    keyBooks: ['TS Grewal Double Entry Book Keeping', 'DK Goel Accountancy', 'NCERT Accountancy', 'Frank ISC Accountancy'],
    pedagogyFocus: 'Journal entry foundation logic, ledger format discipline, adjustment entries, and balance sheet reconciliation.',
    examFocus: ['CBSE Class 12 Accountancy 100/100 Target', 'ISC Class 12 Accounts', 'CUET Commerce Domain', 'CA Foundation Basics'],
  },
  {
    slug: 'economics',
    name: 'Economics (Micro, Macro & Indian Economy)',
    category: 'COMMERCE',
    targetClasses: 'Class 9 to 12 & CUET',
    curriculumTopics: ['Macroeconomics: National Income Accounting', 'Money, Banking & Government Budget', 'Microeconomics: Consumer Equilibrium & Elasticity', 'Indian Economic Development Since 1947', 'Foreign Exchange Rate & BOP'],
    keyBooks: ['Sandeep Garg Macroeconomics', 'VK Ohri & TR Jain', 'NCERT Indian Economic Development', 'Radha Bahuguna'],
    pedagogyFocus: 'Economic curve graphs, analytical table interpretation, numerical national income formulas, and case study evaluations.',
    examFocus: ['CBSE Class 12 Economics Boards', 'ISC Economics', 'CUET Economics 200/200 Percentile', 'IB DP Economics HL/SL'],
  },
  {
    slug: 'business-studies',
    name: 'Business Studies & Management',
    category: 'COMMERCE',
    targetClasses: 'Class 11 & 12',
    curriculumTopics: ['Principles of Management (Fayol & Taylor)', 'Financial Management & Capital Structure', 'Marketing Management & 4Ps Mix', 'Planning, Organizing, Staffing & Controlling', 'Consumer Protection Act'],
    keyBooks: ['Poonam Gandhi Business Studies', 'Subhash Dey', 'NCERT Business Studies', 'CB Gupta'],
    pedagogyFocus: 'Real-world business case study cracking, keyword highlighting for CBSE marking schemes, and mnemonic retention aids.',
    examFocus: ['CBSE Class 12 BST Board Exam', 'ISC Commerce', 'CUET Business Studies'],
  },
  {
    slug: 'computer-science-python',
    name: 'Computer Science, Python & Coding',
    category: 'STEM',
    targetClasses: 'Class 8 to 12 & Coding for Kids',
    curriculumTopics: ['Python Core Syntax & Data Structures (List, Tuple, Dict)', 'Functions & Exception Handling', 'File Handling (Text, Binary, CSV)', 'MySQL Database Connectivity with Python', 'Data Structures (Stack Implementation) & Computer Networks'],
    keyBooks: ['Sumita Arora Computer Science with Python', 'Preeti Arora', 'NCERT CS', 'Oswaal Python Question Banks'],
    pedagogyFocus: 'Hands-on live code debugging, algorithm dry-runs, board output questions, and practical project guidance.',
    examFocus: ['CBSE Class 12 CS Python 70/70 Theory & 30/30 Practical', 'ISC Computer Science (Java)', 'Cambridge Computer Science'],
  },
  {
    slug: 'english-literature-language',
    name: 'English Core, Literature & Grammar',
    category: 'LANGUAGES',
    targetClasses: 'Class 6 to 12',
    curriculumTopics: ['Advanced Reading Comprehension & Note Making', 'Writing Skills (Article, Notice, Report, Letter, Speech)', 'Flamingo & Vistas Prose and Poetry Analysis', 'Grammar Correction & Editing', 'Critical Literary Analysis'],
    keyBooks: ['NCERT Flamingo & Vistas', 'Wren & Martin High School Grammar', 'All in One English Core', 'Oswaal CBSE English'],
    pedagogyFocus: 'Vocabulary enhancement, structured essay frameworks, poetry theme deconstruction, and full-mark answer formatting.',
    examFocus: ['CBSE 10th & 12th Board English 95+', 'ICSE & ISC English Literature', 'IB DP English Language & Literature'],
  },
  {
    slug: 'french-language',
    name: 'French Language (School Curriculum & DELF)',
    category: 'LANGUAGES',
    targetClasses: 'Class 5 to 12 & DELF A1/A2/B1',
    curriculumTopics: ['French Grammar (Temps, Pronoms, Adjectifs)', 'Reading Comprehension & Dialogues', 'Writing Informal & Formal Letters in French', 'Entre Jeunes School Curriculum', 'DELF Exam Preparation'],
    keyBooks: ['Entre Jeunes (CBSE French)', 'Apprenons le Français', 'Echo A1/A2', 'Grammaire Progressive du Français'],
    pedagogyFocus: 'Interactive phonetics, verb conjugation drills, school textbook translation mastery, and conversational fluency.',
    examFocus: ['CBSE Class 9 & 10 Board French', 'IB French Ab Initio / B SL', 'DELF Junior A1 & A2 Certifications'],
  },
  {
    slug: 'german-language',
    name: 'German Language',
    category: 'LANGUAGES',
    targetClasses: 'Class 6 to 12 & Goethe Zertifikat',
    curriculumTopics: ['German Grammar (Kasus: Nominativ, Akkusativ, Dativ)', 'Modalverben & Perfekt Tense', 'Vocabulary for School Themes', 'Goethe Fit in Deutsch A1/A2 Prep'],
    keyBooks: ['Beste Freunde (CBSE German)', 'Planetino', 'Netzwerk Deutsch', 'Fit fürs Goethe-Zertifikat'],
    pedagogyFocus: 'Grammar logic, article gender retention, reading comprehension, and pronunciation training.',
    examFocus: ['CBSE School German Exams', 'Goethe-Institut Fit in Deutsch A1/A2', 'IB German B'],
  },
  {
    slug: 'social-studies-history-geography',
    name: 'Social Studies (History, Civics, Geography)',
    category: 'HUMANITIES',
    targetClasses: 'Class 6 to 10',
    curriculumTopics: ['Nationalism in Europe & India', 'Resources & Sustainable Development', 'Democracy & Power Sharing', 'Economic Sectors & Globalization', 'Map Pointing Skills'],
    keyBooks: ['NCERT Social Science (4 Books)', 'Golden Social Science', 'All in One SST'],
    pedagogyFocus: 'Timeline visualization, map work mastery, 5-mark answer structuring with subheadings, and historical cause-effect logic.',
    examFocus: ['CBSE Class 10 Board Social Science 95+ Score', 'ICSE History & Geography Class 10'],
  },
  {
    slug: 'psychology',
    name: 'Psychology',
    category: 'HUMANITIES',
    targetClasses: 'Class 11 & 12',
    curriculumTopics: ['Variations in Psychological Attributes', 'Self & Personality Assessment', 'Meeting Life Challenges & Stress', 'Psychological Disorders & Psychotherapy', 'Attitude & Social Cognition'],
    keyBooks: ['NCERT Psychology Class 11 & 12', 'Morgan & King Introduction to Psychology', 'Robert Baron Psychology'],
    pedagogyFocus: 'Psychological case studies, DSM-5 diagnostic frameworks, experiment reporting, and viva examination prep.',
    examFocus: ['CBSE Class 12 Psychology Boards', 'ISC Psychology', 'CUET Psychology Domain'],
  },
  {
    slug: 'vedic-maths-abacus',
    name: 'Vedic Maths & Speed Mental Math',
    category: 'SPECIALIZED',
    targetClasses: 'Class 3 to 9',
    curriculumTopics: ['Rapid Multiplication Sutras (Urdhva Tiryagbhyam)', 'Instant Square Roots & Cube Roots in Seconds', 'Mental Addition & Subtraction Techniques', 'Algebraic Speed Factorization', 'Competitive Math Foundation'],
    keyBooks: ['Vedic Mathematics by Bharati Krishna Tirtha', 'Speed Math for Kids'],
    pedagogyFocus: '10x faster mental calculation, elimination of finger counting, and joyful math Olympiad readiness.',
    examFocus: ['Math Olympiads (IMO, NSTSE)', 'School Rapid Math Competitions', 'Foundational IQ Development'],
  },
];

// =========================================================================
// 3. GRADE LEVELS & EDUCATIONAL TRACKS
// =========================================================================
export const PSEO_GRADE_LEVELS: PSEOGradeLevel[] = [
  {
    slug: 'primary-classes-1-to-5',
    name: 'Primary Classes (Class 1 to 5)',
    classes: 'Class 1, 2, 3, 4, 5',
    baseHourlyRate: 600,
    baseMonthlyRate: 6500,
    focusArea: 'Foundational reading, writing, mental maths, phonics, and homework assistance.',
  },
  {
    slug: 'middle-school-classes-6-to-8',
    name: 'Middle School (Class 6 to 8)',
    classes: 'Class 6, 7, 8',
    baseHourlyRate: 700,
    baseMonthlyRate: 8000,
    focusArea: 'Concept building in Science, Maths, English grammar, and foreign languages for CBSE/ICSE/IB.',
  },
  {
    slug: 'secondary-class-9-and-10',
    name: 'Secondary School (Class 9 & 10 Boards)',
    classes: 'Class 9, Class 10 (Board Prep)',
    baseHourlyRate: 850,
    baseMonthlyRate: 10000,
    focusArea: 'CBSE 10th Board 95+ target, ICSE syllabus mastery, NCERT Exemplar, and sample papers.',
  },
  {
    slug: 'senior-secondary-class-11-and-12',
    name: 'Senior Secondary (Class 11 & 12 Science & Commerce)',
    classes: 'Class 11, Class 12 (Board & Entrance)',
    baseHourlyRate: 1100,
    baseMonthlyRate: 13500,
    focusArea: 'Board exam perfection, HC Verma, TS Grewal, reaction mechanisms, and entrance foundation.',
  },
  {
    slug: 'ib-igcse-international-curriculum',
    name: 'IB Diploma & Cambridge IGCSE',
    classes: 'IB MYP, IB DP (HL/SL), Cambridge IGCSE',
    baseHourlyRate: 1500,
    baseMonthlyRate: 18000,
    focusArea: 'Internal Assessments (IA), Extended Essays (EE), past papers, and criterion-based grading.',
  },
  {
    slug: 'neet-jee-competitive-foundation',
    name: 'NEET Medical & JEE Main Engineering Prep',
    classes: 'Class 11, 12 & Droppers',
    baseHourlyRate: 1400,
    baseMonthlyRate: 16500,
    focusArea: 'High-speed numerical solving, negative marking reduction, past 15-year papers, and formula retention.',
  },
];
