const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

const GURGAON_LOCALITIES = [
  { slug: 'dlf-phase-5', name: 'DLF Phase 5', pincode: '122009', landmark: 'The Aralias, Magnolias, Horizon Centre' },
  { slug: 'golf-course-road', name: 'Golf Course Road', pincode: '122002', landmark: 'One Horizon, Mega Mall, Sector 42' },
  { slug: 'dlf-phase-1', name: 'DLF Phase 1', pincode: '122002', landmark: 'Silver Oaks, Mega Mall, Qutab Plaza' },
  { slug: 'dlf-phase-2', name: 'DLF Phase 2', pincode: '122002', landmark: 'Cyber City, Oakwood, Jacaranda Marg' },
  { slug: 'dlf-phase-4', name: 'DLF Phase 4', pincode: '122009', landmark: 'Galleria Market, Supermart, Ridgewood' },
  { slug: 'sohna-road', name: 'Sohna Road', pincode: '122018', landmark: 'Vatika City, Malibu Town, Subhash Chowk' },
  { slug: 'nirvana-country', name: 'Nirvana Country (Sector 50)', pincode: '122018', landmark: 'South City 2, Unitech Fresco' },
  { slug: 'sector-56', name: 'Sector 56', pincode: '122011', landmark: 'HUDA Market, Rapid Metro, Kendriya Vihar' },
  { slug: 'sector-57', name: 'Sector 57', pincode: '122003', landmark: 'Hong Kong Bazaar, Sushant Lok 3' },
  { slug: 'sector-14', name: 'Sector 14 & Old DLF', pincode: '122001', landmark: 'SSSAM Academy Center, HUDA Market' },
  { slug: 'sector-48', name: 'Sector 48', pincode: '122018', landmark: 'Vipul Greens, Central Park, JMD Megapolis' },
  { slug: 'palam-vihar', name: 'Palam Vihar', pincode: '122017', landmark: 'Ansal Plaza, Chiranjiv Bharati School' },
  { slug: 'sector-82', name: 'New Gurgaon (Sector 82-84)', pincode: '122004', landmark: 'Vatika India Next, Mapsko' },
  { slug: 'sushant-lok-1', name: 'Sushant Lok 1', pincode: '122009', landmark: 'Gold Souk, Vyapar Kendra, Fortis' },
];

const TUTORS_DATA = [
  {
    id: 'tut-1',
    name: 'Rohit Sharma',
    phone: '9811204921',
    email: 'rohit.sharma@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'M.Sc. Mathematics (Delhi University)',
    experienceYears: 7,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['Mathematics', 'Physics']),
    classes: JSON.stringify(['Class 9 & 10 (CBSE / ICSE Board)', 'Class 11 & 12 (Board & JEE/NEET)']),
    boards: JSON.stringify(['CBSE', 'ICSE', 'IB (International Baccalaureate)']),
    serviceAreas: JSON.stringify(['DLF Phase 5', 'Golf Course Road', 'Sector 56', 'Sushant Lok 1']),
    travelRadiusKm: 6,
    hourlyRateHome: 900,
    hourlyRateOnline: 600,
    monthlyRateMin: 7500,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.95,
    totalReviews: 38,
    bio: 'Former coaching faculty specializing in conceptual Maths and Board exam 95+ score strategy. 100% personalized pacing for each child.',
    kycLast4: '4589',
  },
  {
    id: 'tut-2',
    name: 'Dr. Ananya Sengupta',
    phone: '9873194021',
    email: 'ananya.sengupta@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'Ph.D. Organic Chemistry (IIT Delhi Alum)',
    experienceYears: 9,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['Chemistry', 'Biology']),
    classes: JSON.stringify(['Class 11 & 12 (Board & JEE/NEET)', 'IIT-JEE / NEET Special Mentorship', 'IB / IGCSE / Cambridge Elite']),
    boards: JSON.stringify(['CBSE', 'IB (International Baccalaureate)', 'IGCSE / Cambridge']),
    serviceAreas: JSON.stringify(['DLF Phase 1', 'DLF Phase 4', 'Nirvana Country', 'Sohna Road']),
    travelRadiusKm: 8,
    hourlyRateHome: 1200,
    hourlyRateOnline: 800,
    monthlyRateMin: 9500,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 5.0,
    totalReviews: 52,
    bio: 'Specialist in organic mechanisms & NEET numericals. Taught 120+ top rankers in Gurgaon over 9 years.',
    kycLast4: '7821',
  },
  {
    id: 'tut-3',
    name: 'Priyanka Verma',
    phone: '9517447689',
    email: 'priyanka.verma@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'B.Tech CS (NSUT) & SSSAM Coding Mentor',
    experienceYears: 5,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['Computer Science & Python', 'Web Development & Coding (SSSAM)', 'Mathematics']),
    classes: JSON.stringify(['Class 9 & 10 (CBSE / ICSE Board)', 'Class 11 & 12 (Board & JEE/NEET)', 'Coding & AI for Kids']),
    boards: JSON.stringify(['CBSE', 'ICSE', 'IGCSE / Cambridge']),
    serviceAreas: JSON.stringify(['Sector 14 & Old DLF', 'Sector 48', 'Palam Vihar', 'DLF Phase 2']),
    travelRadiusKm: 7,
    hourlyRateHome: 1000,
    hourlyRateOnline: 700,
    monthlyRateMin: 8000,
    isVerified: true,
    hasPoliceCheck: false,
    rating: 4.92,
    totalReviews: 29,
    bio: 'Lead Python instructor at SSSAM Academy Sector 14. Mentoring school students in CBSE Python, algorithmic thinking, and building live web projects.',
    kycLast4: '3312',
  },
  {
    id: 'tut-4',
    name: 'Priyanka Aggarwal',
    phone: '9810482019',
    email: 'priyanka.aggarwal@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'M.Com, Chartered Accountant (Inter)',
    experienceYears: 6,
    teachingMode: 'OFFLINE_HOME',
    subjects: JSON.stringify(['Accountancy & Commerce', 'Economics']),
    classes: JSON.stringify(['Class 11 & 12 (Board & JEE/NEET)', 'Class 9 & 10 (CBSE / ICSE Board)']),
    boards: JSON.stringify(['CBSE', 'ISC / ICSE']),
    serviceAreas: JSON.stringify(['Sector 56', 'Sector 57', 'Golf Course Road', 'DLF Phase 5']),
    travelRadiusKm: 5,
    hourlyRateHome: 850,
    hourlyRateOnline: 600,
    monthlyRateMin: 7000,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.90,
    totalReviews: 24,
    bio: 'Specialist in Class 11-12 CBSE Accounts & Economics. Simplifies balance sheets and cash flow statements with practical company examples.',
    kycLast4: '9901',
  },
  {
    id: 'tut-5',
    name: 'Vikram Malhotra',
    phone: '9899124012',
    email: 'vikram.malhotra@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'B.Tech Mechanical (IIT Roorkee)',
    experienceYears: 8,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['Physics', 'Mathematics']),
    classes: JSON.stringify(['Class 11 & 12 (Board & JEE/NEET)', 'Class 9 & 10 (CBSE / ICSE Board)']),
    boards: JSON.stringify(['CBSE', 'ICSE', 'IB (International Baccalaureate)']),
    serviceAreas: JSON.stringify(['Nirvana Country (Sector 50)', 'Sohna Road', 'Sector 48', 'Sector 57']),
    travelRadiusKm: 8,
    hourlyRateHome: 1100,
    hourlyRateOnline: 750,
    monthlyRateMin: 9000,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.98,
    totalReviews: 44,
    bio: 'IITian Physics specialist with 8 years of coaching experience in Gurgaon. Master in rotational dynamics, electromagnetism, and board numericals.',
    kycLast4: '6654',
  },
  {
    id: 'tut-6',
    name: 'Meenakshi Sundaram',
    phone: '9811263012',
    email: 'meenakshi.s@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'M.A. English Literature (Lady Shri Ram College, DU)',
    experienceYears: 6,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['English Language & Literature', 'Social Science (History, Geo, Civics, Eco)']),
    classes: JSON.stringify(['Class 9 & 10 (CBSE / ICSE Board)', 'Class 11 & 12 (Board & JEE/NEET)', 'Class 6 - 8 (Middle School)']),
    boards: JSON.stringify(['CBSE', 'ICSE', 'IB (International Baccalaureate)', 'IGCSE / Cambridge']),
    serviceAreas: JSON.stringify(['DLF Phase 5', 'DLF Phase 4', 'Golf Course Road', 'Sector 56']),
    travelRadiusKm: 6,
    hourlyRateHome: 800,
    hourlyRateOnline: 550,
    monthlyRateMin: 6500,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.96,
    totalReviews: 32,
    bio: 'Specialist in English writing skills, CBSE board literature answers, and critical reading. Proven 95+ score track record.',
    kycLast4: '1123',
  },
  {
    id: 'tut-7',
    name: 'Rajesh Kumar Gupta',
    phone: '9818833912',
    email: 'rajesh.gupta@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'M.Sc. Mathematics & Statistics (IIT Kanpur)',
    experienceYears: 10,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['Mathematics', 'JEE Main & Advanced Maths', 'IB Diploma Math (AA / AI HL & SL)']),
    classes: JSON.stringify(['Class 9 & 10 (CBSE / ICSE Board)', 'Class 11 & 12 (Board & JEE/NEET)', 'IB / IGCSE / Cambridge Elite']),
    boards: JSON.stringify(['CBSE', 'IB (International Baccalaureate)', 'IGCSE / Cambridge']),
    serviceAreas: JSON.stringify(['DLF Phase 1', 'DLF Phase 2', 'Sector 14 & Old DLF', 'Palam Vihar']),
    travelRadiusKm: 8,
    hourlyRateHome: 1250,
    hourlyRateOnline: 850,
    monthlyRateMin: 10000,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 5.0,
    totalReviews: 61,
    bio: 'Ex-Bansal faculty with 10+ years mentoring IIT-JEE aspirants and IB Diploma students in advanced Calculus and Algebra.',
    kycLast4: '8872',
  },
  {
    id: 'tut-8',
    name: 'Dr. Shalini Kapoor',
    phone: '9810992314',
    email: 'shalini.kapoor@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'M.Sc. & Ph.D. Zoology (AIIMS / DU)',
    experienceYears: 8,
    teachingMode: 'BOTH',
    subjects: JSON.stringify(['Biology', 'NEET Biology Prep', 'IB Biology & Environmental Science']),
    classes: JSON.stringify(['Class 11 & 12 (Board & JEE/NEET)', 'Class 9 & 10 (CBSE / ICSE Board)']),
    boards: JSON.stringify(['CBSE', 'ICSE', 'IB (International Baccalaureate)']),
    serviceAreas: JSON.stringify(['Sohna Road', 'Nirvana Country (Sector 50)', 'Sector 48', 'Sector 57']),
    travelRadiusKm: 7,
    hourlyRateHome: 1150,
    hourlyRateOnline: 800,
    monthlyRateMin: 9200,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.97,
    totalReviews: 47,
    bio: 'NEET Botany & Zoology specialist. 360/360 biology strategy builder with comprehensive NCERT diagram breakdown.',
    kycLast4: '5543',
  },
  {
    id: 'tut-9',
    name: 'Amanpreet Singh',
    phone: '9811002233',
    email: 'amanpreet.singh@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'B.Ed & M.Sc. Physics (Punjab University)',
    experienceYears: 6,
    teachingMode: 'OFFLINE_HOME',
    subjects: JSON.stringify(['Physics', 'Science (Class 1 - 10 Combined)']),
    classes: JSON.stringify(['Class 9 & 10 (CBSE / ICSE Board)', 'Class 6 - 8 (Middle School)']),
    boards: JSON.stringify(['CBSE', 'ICSE']),
    serviceAreas: JSON.stringify(['Sector 14 & Old DLF', 'Sector 48', 'Palam Vihar', 'DLF Phase 1']),
    travelRadiusKm: 6,
    hourlyRateHome: 850,
    hourlyRateOnline: 600,
    monthlyRateMin: 7000,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.88,
    totalReviews: 21,
    bio: 'Hands-on practical physics teacher. Uses live everyday experiment demonstrations to build deep intuition for Newton laws and Optics.',
    kycLast4: '2290',
  },
  {
    id: 'tut-10',
    name: 'Neha Chawla',
    phone: '9811445566',
    email: 'neha.chawla@tuitionforhome.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    introVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    highestDegree: 'B.El.Ed (DU) & Montessori Certified',
    experienceYears: 5,
    teachingMode: 'OFFLINE_HOME',
    subjects: JSON.stringify(['All Primary Subjects (Class 1 - 5)', 'Abacus & Vedic Mathematics', 'English Language & Literature']),
    classes: JSON.stringify(['Class 1 - 5 (Primary Foundation)', 'Class 6 - 8 (Middle School)']),
    boards: JSON.stringify(['CBSE', 'ICSE', 'IB (International Baccalaureate)']),
    serviceAreas: JSON.stringify(['DLF Phase 5', 'Golf Course Road', 'Sushant Lok 1', 'Sector 56']),
    travelRadiusKm: 5,
    hourlyRateHome: 750,
    hourlyRateOnline: 500,
    monthlyRateMin: 6000,
    isVerified: true,
    hasPoliceCheck: true,
    rating: 4.94,
    totalReviews: 35,
    bio: 'Gentle, patient primary home tutor specializing in reading phonics, handwriting improvement, and foundational mental math.',
    kycLast4: '4410',
  },
];

async function main() {
  console.log('🚀 Initializing & Seeding Complete Database...');

  // 1. Seed Global Platform Config
  await prisma.platformConfig.upsert({
    where: { id: 'global_config' },
    update: {},
    create: {
      id: 'global_config',
      baseVerificationFee: 999,
      isOfferActive: true,
      offerDiscountPercent: 100,
      offerTitle: 'Academic Session 2026-27 Special Drive',
      offerSubtext: '100% Verification Fee Waiver for Gurgaon & NCR Educators',
      officeAddress: 'M24 Ground Floor, Old DLF Colony, Sector 14, Gurugram, Haryana 122001',
      helplinePhones: '+91 95174 47689, +91 92170 31899',
      supportEmail: 'info@sssamacademy.com',
    },
  });

  // 2. Seed Locality SEO Pages
  for (const loc of GURGAON_LOCALITIES) {
    await prisma.localitySEO.upsert({
      where: { slug: loc.slug },
      update: {},
      create: {
        slug: loc.slug,
        name: loc.name,
        city: 'Gurgaon',
        pincode: loc.pincode,
        metaTitle: `Best Home Tutors in ${loc.name}, Gurgaon | SSSAM Academy`,
        metaDesc: `Find verified home and online tutors in ${loc.name}, Gurgaon (${loc.landmark}). 1 Free Demo Class + 100% Replacement Guarantee.`,
        h1Heading: `Best Home Tutors in ${loc.name}, Gurgaon`,
        contentBody: `Connect with verified educators serving residential communities in and around ${loc.landmark}.`,
        isActive: true,
      },
    });
  }

  // 3. Seed Default Admin User
  const defaultPasswordHash = await bcrypt.hash('admin123', 10);
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@sssamacademy.com' },
    update: {},
    create: {
      name: 'Super Admin',
      email: 'admin@sssamacademy.com',
      passwordHash: defaultPasswordHash,
      phone: '+91 95174 47689',
      role: 'SUPER_ADMIN',
    },
  });

  // 4. Seed Counselor Accounts
  const counselors = [
    { name: 'Pooja Sharma', email: 'pooja.sharma@sssamacademy.com', phone: '+91 98112 34567', role: 'TELECALLER' },
    { name: 'Amit Kumar', email: 'amit.kumar@sssamacademy.com', phone: '+91 98765 43210', role: 'TELECALLER' },
    { name: 'Sneha Verma', email: 'sneha.verma@sssamacademy.com', phone: '+91 99887 76655', role: 'TELECALLER' },
    { name: 'Rahul Dev', email: 'rahul.dev@sssamacademy.com', phone: '+91 97110 09988', role: 'TELECALLER' },
  ];

  let firstCounselorId = adminUser.id;
  for (const c of counselors) {
    const user = await prisma.user.upsert({
      where: { email: c.email },
      update: {},
      create: {
        name: c.name,
        email: c.email,
        passwordHash: defaultPasswordHash,
        phone: c.phone,
        role: 'TELECALLER',
      },
    });
    if (c.name === 'Pooja Sharma') firstCounselorId = user.id;
  }

  // 5. Seed Verified Tutors & Tutor Profiles
  for (const tut of TUTORS_DATA) {
    const tutorUser = await prisma.user.upsert({
      where: { email: tut.email },
      update: {},
      create: {
        name: tut.name,
        email: tut.email,
        phone: tut.phone,
        passwordHash: defaultPasswordHash,
        role: 'TUTOR',
      },
    });

    const tutorProfile = await prisma.tutorProfile.upsert({
      where: { userId: tutorUser.id },
      update: {},
      create: {
        id: tut.id,
        userId: tutorUser.id,
        avatarUrl: tut.avatarUrl,
        introVideoUrl: tut.introVideoUrl,
        highestDegree: tut.highestDegree,
        experienceYears: tut.experienceYears,
        teachingMode: tut.teachingMode,
        subjects: tut.subjects,
        classes: tut.classes,
        boards: tut.boards,
        serviceAreas: tut.serviceAreas,
        travelRadiusKm: tut.travelRadiusKm,
        hourlyRateHome: tut.hourlyRateHome,
        hourlyRateOnline: tut.hourlyRateOnline,
        monthlyRateMin: tut.monthlyRateMin,
        isVerified: tut.isVerified,
        hasPoliceCheck: tut.hasPoliceCheck,
        rating: tut.rating,
        totalReviews: tut.totalReviews,
        bio: tut.bio,
        status: 'ACTIVE_VERIFIED',
      },
    });

    // KYC record
    await prisma.tutorKYC.upsert({
      where: { tutorId: tutorProfile.id },
      update: {},
      create: {
        tutorId: tutorProfile.id,
        idType: 'AADHAAR_MASKED',
        idLast4: tut.kycLast4,
        idDocUrl: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=600&auto=format&fit=crop&q=80',
        verificationDate: new Date(),
        verifiedByAdmin: adminUser.id,
      },
    });
  }

  // 6. Seed Sample Leads with Dynamic Parent Inquiries
  const sampleLeads = [
    {
      id: 'LD-101',
      parentName: 'Sunita Rao',
      parentPhone: '9811200111',
      parentEmail: 'sunita.rao@gmail.com',
      gradeClass: 'Class 10',
      subjectsNeeded: JSON.stringify(['Mathematics', 'Physics']),
      board: 'CBSE',
      locality: 'DLF Phase 5, Gurgaon',
      preferredMode: 'OFFLINE_HOME',
      budgetMonthly: 8000,
      status: 'DEMO_SCHEDULED',
      assignedCallerId: firstCounselorId,
      assignedTutorId: 'tut-1',
      notes: 'Parent requested demo class on Saturday at 5 PM. Rohit Sharma assigned.',
    },
    {
      id: 'LD-102',
      parentName: 'Vikram Ahuja',
      parentPhone: '9873100222',
      parentEmail: 'vikram.ahuja@outlook.com',
      gradeClass: 'Class 12',
      subjectsNeeded: JSON.stringify(['Chemistry', 'Biology / NEET']),
      board: 'CBSE',
      locality: 'Nirvana Country (Sector 50)',
      preferredMode: 'OFFLINE_HOME',
      budgetMonthly: 10000,
      status: 'TUITION_CONFIRMED',
      assignedCallerId: firstCounselorId,
      assignedTutorId: 'tut-2',
      notes: 'Tuition confirmed. Advance fee ₹10,000 received. Ongoing classes MWF 6 PM.',
    },
    {
      id: 'LD-103',
      parentName: 'Deepak Malhotra',
      parentPhone: '9899100333',
      parentEmail: 'deepak.m@gmail.com',
      gradeClass: 'Class 8',
      subjectsNeeded: JSON.stringify(['Mathematics', 'Science']),
      board: 'ICSE',
      locality: 'Sector 56, Gurgaon',
      preferredMode: 'OFFLINE_HOME',
      budgetMonthly: 7000,
      status: 'NEW_LEAD',
      assignedCallerId: firstCounselorId,
      notes: 'Fresh inquiry from website. Seeking experienced teacher for ICSE Class 8.',
    },
    {
      id: 'LD-104',
      parentName: 'Megha Singhal',
      parentPhone: '9810500444',
      parentEmail: 'megha.singhal@yahoo.com',
      gradeClass: 'Class 11',
      subjectsNeeded: JSON.stringify(['Accountancy', 'Economics']),
      board: 'CBSE',
      locality: 'Golf Course Road, Gurgaon',
      preferredMode: 'OFFLINE_HOME',
      budgetMonthly: 9000,
      status: 'TUITION_CONFIRMED',
      assignedCallerId: firstCounselorId,
      assignedTutorId: 'tut-4',
      notes: 'Classes running smoothly with Priyanka Aggarwal since last month.',
    },
    {
      id: 'LD-105',
      parentName: 'Rajesh Nair',
      parentPhone: '9818800555',
      parentEmail: 'rajesh.nair@corp.in',
      gradeClass: 'Class 4',
      subjectsNeeded: JSON.stringify(['All Primary Subjects', 'Abacus']),
      board: 'IB (International Baccalaureate)',
      locality: 'DLF Phase 4, Gurgaon',
      preferredMode: 'OFFLINE_HOME',
      budgetMonthly: 7500,
      status: 'CALL_SCHEDULED',
      assignedCallerId: firstCounselorId,
      notes: 'Call scheduled today at 4:30 PM to discuss IB primary syllabus requirements.',
    },
  ];

  for (const l of sampleLeads) {
    await prisma.lead.upsert({
      where: { id: l.id },
      update: {},
      create: {
        id: l.id,
        parentName: l.parentName,
        parentPhone: l.parentPhone,
        parentEmail: l.parentEmail,
        gradeClass: l.gradeClass,
        subjectsNeeded: l.subjectsNeeded,
        board: l.board,
        locality: l.locality,
        preferredMode: l.preferredMode,
        budgetMonthly: l.budgetMonthly,
        status: l.status,
        assignedCallerId: l.assignedCallerId,
        assignedTutorId: l.assignedTutorId,
        notes: l.notes,
        activities: {
          create: [
            {
              actionType: 'STATUS_CHANGE',
              description: `Lead created with initial status: ${l.status}. Remark: ${l.notes}`,
              performedBy: 'System Seeder',
            },
          ],
        },
      },
    });
  }

  console.log('✅ Database completely initialized and seeded with all tables and records!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
